kind: Namespace
apiVersion: v1
metadata:
  name: landing
---
kind: Secret
apiVersion: v1
metadata:
    name: system-ci-secret
    namespace: landing
data:
    .dockerconfigjson: <SECRET>
type: kubernetes.io/dockerconfigjson
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: api
  namespace: landing
  labels:
    app: api
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: registry.kthcloud.com/system/landing-api
          imagePullPolicy: Always
      imagePullSecrets:
        - name: system-ci-secret
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: landing
  labels:
    app: api
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: api