---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: landing
  labels:
    app.kubernetes.io/name: api
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: api